version: "3"


services:
  back:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./back:/back
    command: >
      sh -c "python manage.py manage.py runserver 0.0.0.0:8000"